### ISSUE TITLE
Update does not save movie poster

### ISSUE THREAD

**Issue by kkayacan** [jreklund/php4dvd#39]
Delete poster from /movies folder. Select edit -> update on movie page. Poster appears. When you hit save, poster disappears.

**Comment by jreklund** [comment]
It will only download poster from movies/tv-shows if it's a new title. If you wan't it to download it again (and not just show it). You will need to check:
Poster (IMDb) - Download from IMDb

It's a fail safe so that it dosen't delete a custom poster. But there are no built in check that it actually exists one. Why would you delete it? :-)

**Comment by kkayacan** [comment]
I actually wanted to check a backup & restore scenario. I exported database with phpmyadmin. I did a fresh install to somewhere else. Then deleted the tables and imported database with phpmyadmin. Only missing thing is posters.

**Comment by kkayacan** [comment]
Still a lot of work for a large collection but download from imdb check on edit page will do. Thanks.
