### ISSUE TITLE
How to modify the software? (add / remove metadata)

### ISSUE THREAD

**Issue by b1fly** [jreklund/php4dvd#80]
Thank you for your selfless open source！
How to remove CAST, there is too much content to show and I guess it will affect the loading speed.
How to transfer all Plot outline Personal notes Plots to below movie details?

Is it possible to add a similar form? For example, the picture below, you can customize the text + link
![image](https://user-images.githubusercontent.com/108970034/186359765-b2ecb1f8-e515-4411-ab58-8da4d08e9dae.png)

**Comment by jreklund** [comment]
Hi, I'm not the original creator of this software. Version 1.0 and 2.0 where created by someone else. You can see all attributions in the  the readme.

As the software are using a quite old database schematics (if you name aren't Amazon) you should have no problems rendering individual movie/tv-show pages. It's just one table containing all data. It's just a foreach loop rending all cast member names. No additional database lookup.

You can remove it from template in case you don't want to see it. Or limit the foreach with `numberOfCast` config option.
/tpl/default/movies/movie.html

This will however not stop it from grabbing it from the database, in that case you need to modify `get` method.
/lib/db/Movies.class.php

That will however affect all other features on the site, like updating movies, as it will no get cast data anywhere.

Usually slow loading speed only affect the movie collection screen and search function due to the software not having a cache engine and not optimized database layout. 
___________

I guess you mean the collection page where all movies are displayed, as the individual movie details contain all data that's in the system. If not, you need to be more specific.

You can change what columns to retrieve from the database from the search method (collection page) in this file:
/includes/movie.search.inc.php#L132

And add it to your template:
/tpl/default/movies/movies/*
___________

Everything can be added or removed, it's just code after all. It's beyond the scope of this software and you will need to learn to code yourself or hire someone to do it for you.

**Comment by b1fly** [comment]
Thanks for your reply, is there any other way to speed up loading, cache.
Yes, because there are so many names shown, usually just starring and director is enough, I just feel like it might affect the database and website loading speed.

**Comment by jreklund** [comment]
No, there are no built in cache. You can however set up nginx, Varnish Cache or similar software to cache static pages. You need to force the cache however, as there aren't any correct headers being sent by the application for this kind of software. If you end up forcing all pages to be cached, you need a separate url to be able to login and add titles. 

Getting a faster server are also an option, so it can handle more traffic.

**Comment by b1fly** [comment]
> No, there are no built in cache. You can however set up nginx, Varnish Cache or similar software to cache static pages. You need to force the cache however, as there aren't any correct headers being sent by the application for this kind of software. If you end up forcing all pages to be cached, you need a separate url to be able to login and add titles.
> 
> Getting a faster server are also an option, so it can handle more traffic.

Thank you for your reply, maybe a third -party tool is a choice.
I want to know how to modify Personal Notes into a column form similar to tables? Just like the picture below, I can freely add address or magnetic links to each step in the background.
![2022-08-30_19-49-51](https://user-images.githubusercontent.com/108970034/187429488-3ada2327-46b0-4a22-b8bd-49086638a7ec.jpg)

**Comment by jreklund** [comment]
I'm afraid I won't be doing a write up on how to code all that. Take a look on how e.g. producer are used in `/tpl/default/movies/movie.html`, it would be a similar process to split it by new line and turn it into urls.

**Comment by b1fly** [comment]
> I'm afraid I won't be doing a write up on how to code all that. Take a look on how e.g. producer are used in `/tpl/default/movies/movie.html`, it would be a similar process to split it by new line and turn it into urls.

Well, I don't know the code and this is challenging for me.

**Comment by jreklund** [comment]
> Well, I don't know the code and this is challenging for me.

I won't put hours of code into something I won't use or add to the software itself. I'm not available for contract work at this time, so in case you can't code it yourself, you need to hire someone else.
