### ISSUE TITLE
Remove all filters at once

### ISSUE THREAD

**Issue by Bloodsoul** [jreklund/php4dvd#9]
If you select filters and write a movie title, you get a filtered list for the selected filters. If you reload the site or are willing to reset it to display all, it is necessary to remove all the filters manually one by one.

A little link or a button to remove all the filters would be nice to have.

**Comment by jreklund** [comment]
Just to clarify, what parameters do you want to reset?
- Search
- Categories
- Formats
- Sort by
- Filter by

At the moment there are only the hidden delete-key, that removes the search field.

**Comment by Bloodsoul** [comment]
I think, all of them should be resettable at once.

**Comment by jreklund** [comment]
Added some new shortcuts.
- Focus search field with CTRL+F, CMD+F and F3
- END (in search field) deletes:
  - Search
  - Categories
  - Formats
  - Filter by
 - DELETE (as specified earlier, deletes just search) 

I didn't reset "Sort by" due to the fact I leave it in Added (new-old) position and never change it. Don't want to change it all the time myself. :-)
